language: go
go: 
- 1.3.3
before_install: 
- go get github.com/tools/godep
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get code.google.com/p/go.tools/cmd/cover
- go get code.google.com/p/go.tools/cmd/vet
- go get code.google.com/p/go.tools/cmd/goimports
script: 
- build/ci.sh

